/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import modelos.Empleado;
import modelos.EmpleadoDAO;
import modelos.Usuario;
import modelos.UsuarioDAO;

/**
 *
 * @author USUARO_PC
 */
public class VentanaEmpleados extends javax.swing.JFrame {

    private VentanaPrincipal ventanaPrincipal;

    public VentanaEmpleados(VentanaPrincipal ventanaPrincipal) {
        this.ventanaPrincipal = ventanaPrincipal;
        initComponents();
        cargarDatosEnTabla();          // ← Aquí
        configurarAnchoColumnas();
        configurarCierre();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    private void cargarDatosEnTabla() {
        System.out.println("🔍 Iniciando carga de datos de empleados...");

        // Definir columnas
        String[] columnas = {
            "ID",
            "Cédula",
            "Nombres",
            "Apellidos",
            "Dirección",
            "Teléfono Convencional",
            "Teléfono Celular",
            "Correo Electrónico"
        };

        // Crear modelo de tabla
        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(
                null, columnas
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        try {
            EmpleadoDAO empleadoDAO = new EmpleadoDAO();
            System.out.println("✅ EmpleadoDAO creado correctamente");

            List<Empleado> empleados = empleadoDAO.listarTodos();
            System.out.println("📊 Número de empleados recuperados: " + empleados.size());

            for (Empleado emp : empleados) {
                System.out.println("📄 Empleado: ID=" + emp.getEmpId() + ", Cédula=" + emp.getEmpCedula());
                Object[] fila = {
                    emp.getEmpId(),
                    emp.getEmpCedula(),
                    emp.getEmpNombre(),
                    emp.getEmpApellido(),
                    emp.getEmpDireccion(),
                    emp.getEmpTelefonoConvencional(),
                    emp.getEmpTelefonoCelular(),
                    emp.getEmpCorreoElectronico()
                };
                modelo.addRow(fila);
            }

        } catch (SQLException e) {
            System.out.println("❌ ERROR SQL al cargar empleados: " + e.getMessage());
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Error al cargar los empleados:\n" + e.getMessage(),
                    "Error de base de datos",
                    JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            System.out.println("💥 ERROR GENERAL al cargar empleados: " + e.getMessage());
            e.printStackTrace();
        }

        // Asignar el modelo a la tabla
        jTableEmpleados.setModel(modelo);
        System.out.println("✅ Tabla actualizada con el modelo");
    }

    private void configurarAnchoColumnas() {
        jTableEmpleados.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);

        jTableEmpleados.getColumnModel().getColumn(0).setPreferredWidth(50);   // ID
        jTableEmpleados.getColumnModel().getColumn(1).setPreferredWidth(100);  // Cédula
        jTableEmpleados.getColumnModel().getColumn(2).setPreferredWidth(120);  // Nombre
        jTableEmpleados.getColumnModel().getColumn(3).setPreferredWidth(120);  // Apellido
        jTableEmpleados.getColumnModel().getColumn(4).setPreferredWidth(200);  // Dirección
        jTableEmpleados.getColumnModel().getColumn(5).setPreferredWidth(150);  // Tel Conv.
        jTableEmpleados.getColumnModel().getColumn(6).setPreferredWidth(150);  // Celular
        jTableEmpleados.getColumnModel().getColumn(7).setPreferredWidth(150);  // Correo
        // ← Ya no hay columna 8
    }

    private void configurarCierre() {
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                ventanaPrincipal.setVisible(true);
            }
        });
    }

    public void refrescarTabla() {
        cargarDatosEnTabla(); // Solo recarga los datos
        configurarAnchoColumnas(); // Ajusta el ancho si es necesario
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelClientes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEmpleados = new javax.swing.JTable();
        jButtonRestablecer = new javax.swing.JButton();
        jButtonBuscarEmpleado = new javax.swing.JButton();
        jButtonInsertarEmpleado = new javax.swing.JButton();
        jButtonEliminarEmpleado = new javax.swing.JButton();
        jButtonEditarEmpleado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelClientes.setBackground(new java.awt.Color(51, 153, 255));

        jTableEmpleados.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jTableEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableEmpleados.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTableEmpleados);

        jButtonRestablecer.setText("Restablecer");
        jButtonRestablecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRestablecerActionPerformed(evt);
            }
        });

        jButtonBuscarEmpleado.setText("Buscar");
        jButtonBuscarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarEmpleadoActionPerformed(evt);
            }
        });

        jButtonInsertarEmpleado.setText("Crear");
        jButtonInsertarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertarEmpleadoActionPerformed(evt);
            }
        });

        jButtonEliminarEmpleado.setText("Eliminar");
        jButtonEliminarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarEmpleadoActionPerformed(evt);
            }
        });

        jButtonEditarEmpleado.setText("Editar");
        jButtonEditarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarEmpleadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelClientesLayout = new javax.swing.GroupLayout(jPanelClientes);
        jPanelClientes.setLayout(jPanelClientesLayout);
        jPanelClientesLayout.setHorizontalGroup(
            jPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClientesLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 885, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonEditarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEliminarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonInsertarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRestablecer, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );
        jPanelClientesLayout.setVerticalGroup(
            jPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
            .addGroup(jPanelClientesLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jButtonRestablecer, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonBuscarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonInsertarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonEliminarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonEditarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRestablecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRestablecerActionPerformed
        cargarDatosEnTabla(); // ← Usa el método correcto
        configurarAnchoColumnas();
    }//GEN-LAST:event_jButtonRestablecerActionPerformed

    private void jButtonBuscarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarEmpleadoActionPerformed
        String criterio = javax.swing.JOptionPane.showInputDialog(
                this,
                "Ingrese el nombre, apellido o id del empleado:",
                "Buscar Empleado", // ← ¡Corregido el título!
                javax.swing.JOptionPane.QUESTION_MESSAGE
        );


    }//GEN-LAST:event_jButtonBuscarEmpleadoActionPerformed

    private void jButtonInsertarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertarEmpleadoActionPerformed
        FormularioRegistroEmpleado formulario = new FormularioRegistroEmpleado(this);
        formulario.setVisible(true);
    }//GEN-LAST:event_jButtonInsertarEmpleadoActionPerformed

    private void jButtonEliminarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarEmpleadoActionPerformed

    }//GEN-LAST:event_jButtonEliminarEmpleadoActionPerformed

    private void jButtonEditarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarEmpleadoActionPerformed
        FormularioRegistroEmpleado formulario = new FormularioRegistroEmpleado(this);
        formulario.setVisible(true);
    }//GEN-LAST:event_jButtonEditarEmpleadoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscarEmpleado;
    private javax.swing.JButton jButtonEditarEmpleado;
    private javax.swing.JButton jButtonEliminarEmpleado;
    private javax.swing.JButton jButtonInsertarEmpleado;
    private javax.swing.JButton jButtonRestablecer;
    private javax.swing.JPanel jPanelClientes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEmpleados;
    // End of variables declaration//GEN-END:variables
}
