/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelos.Empleado;
import modelos.EmpleadoDAO;
import modelos.Usuario;
import modelos.UsuarioDAO;

/**
 *
 * @author USUARO_PC
 */
public class VentanaUsuarios extends javax.swing.JFrame {

    private VentanaPrincipal ventanaPrincipal;

    public VentanaUsuarios(VentanaPrincipal ventanaPrincipal) {
        this.ventanaPrincipal = ventanaPrincipal;
        initComponents();
        configurarTabla();
        //configurarAnchoColumnas();
        configurarCierre();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    private void configurarTabla() {
        String[] columnas = {"ID", "Usuario", "Empleado"};

        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(
                null, columnas
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        try {
            UsuarioDAO usuarioDAO = new UsuarioDAO();
            EmpleadoDAO empleadoDAO = new EmpleadoDAO();

            List<Usuario> usuarios = usuarioDAO.listarTodos();

            for (Usuario u : usuarios) {
                // Obtener el empleado asociado
                Empleado emp = empleadoDAO.obtenerPorId(u.getEmpId());
                String nombreEmpleado = (emp != null)
                        ? emp.getEmpNombre() + " " + emp.getEmpApellido()
                        : "Empleado no encontrado";

                Object[] fila = {
                    u.getUsuId(),
                    u.getUsuUsuario(),
                    nombreEmpleado
                };

                modelo.addRow(fila);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                    "Error al cargar los usuarios desde la base de datos:\n" + e.getMessage(),
                    "Error de conexión",
                    JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }

        jTableUsuarios.setModel(modelo);
    }

    public void refrescarTabla() {
        configurarTabla();
    }

    private void mostrarResultadosBusqueda(List<Usuario> usuarios) {
        String[] columnas = {"ID", "Usuario", "Empleado"};

        DefaultTableModel modelo = new DefaultTableModel(null, columnas) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        try {
            EmpleadoDAO empleadoDAO = new EmpleadoDAO();

            for (Usuario u : usuarios) {
                Empleado emp = empleadoDAO.obtenerPorId(u.getEmpId());
                String nombreEmpleado = (emp != null)
                        ? emp.getEmpNombre() + " " + emp.getEmpApellido()
                        : "Empleado no encontrado";

                Object[] fila = {
                    u.getUsuId(),
                    u.getUsuUsuario(),
                    nombreEmpleado
                };
                modelo.addRow(fila);
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }

        jTableUsuarios.setModel(modelo);
    }

    private void configurarCierre() {
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                ventanaPrincipal.setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelClientes3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableUsuarios = new javax.swing.JTable();
        jButtonRestablecer = new javax.swing.JButton();
        jButtonBuscarUsuario = new javax.swing.JButton();
        jButtonCrearUsuario = new javax.swing.JButton();
        jButtonEliminarUsuario = new javax.swing.JButton();
        jButtonEditarEditarUsuario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelClientes3.setBackground(new java.awt.Color(51, 153, 255));

        jTableUsuarios.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jTableUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableUsuarios.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane4.setViewportView(jTableUsuarios);

        jButtonRestablecer.setText("Restablecer");
        jButtonRestablecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRestablecerActionPerformed(evt);
            }
        });

        jButtonBuscarUsuario.setText("Buscar");
        jButtonBuscarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarUsuarioActionPerformed(evt);
            }
        });

        jButtonCrearUsuario.setText("Crear Usuario");
        jButtonCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearUsuarioActionPerformed(evt);
            }
        });

        jButtonEliminarUsuario.setText("Eliminar");
        jButtonEliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarUsuarioActionPerformed(evt);
            }
        });

        jButtonEditarEditarUsuario.setText("Editar");
        jButtonEditarEditarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarEditarUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelClientes3Layout = new javax.swing.GroupLayout(jPanelClientes3);
        jPanelClientes3.setLayout(jPanelClientes3Layout);
        jPanelClientes3Layout.setHorizontalGroup(
            jPanelClientes3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClientes3Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelClientes3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonRestablecer, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEliminarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEditarEditarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 38, Short.MAX_VALUE))
        );
        jPanelClientes3Layout.setVerticalGroup(
            jPanelClientes3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
            .addGroup(jPanelClientes3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jButtonRestablecer, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonBuscarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonCrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonEliminarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonEditarEditarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelClientes3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelClientes3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRestablecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRestablecerActionPerformed
        configurarTabla();
    }//GEN-LAST:event_jButtonRestablecerActionPerformed

    private void jButtonBuscarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarUsuarioActionPerformed
        String criterio = JOptionPane.showInputDialog(
                this,
                "Ingrese el nombre de usuario o nombre del empleado:",
                "Buscar Usuario",
                JOptionPane.QUESTION_MESSAGE
        );

        if (criterio == null || criterio.trim().isEmpty()) {
            return; // Canceló o dejó vacío
        }

        try {
            UsuarioDAO usuarioDAO = new UsuarioDAO();
            EmpleadoDAO empleadoDAO = new EmpleadoDAO();
            List<Usuario> todosUsuarios = usuarioDAO.listarTodos();
            List<Usuario> resultados = new ArrayList<>();

            String busqueda = criterio.trim().toLowerCase();

            for (Usuario u : todosUsuarios) {
                boolean coincide = false;

                // Buscar por nombre de usuario
                if (u.getUsuUsuario().toLowerCase().contains(busqueda)) {
                    coincide = true;
                }

                // Buscar por nombre de empleado
                if (!coincide) {
                    Empleado emp = empleadoDAO.obtenerPorId(u.getEmpId());
                    if (emp != null) {
                        String nombreCompleto = (emp.getEmpNombre() + " " + emp.getEmpApellido()).toLowerCase();
                        if (nombreCompleto.contains(busqueda)) {
                            coincide = true;
                        }
                    }
                }

                if (coincide) {
                    resultados.add(u);
                }
            }

            if (resultados.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "No se encontraron usuarios para: \"" + criterio.trim() + "\"",
                        "Sin resultados",
                        JOptionPane.INFORMATION_MESSAGE);
                configurarTabla(); // Volver a mostrar todos
            } else {
                mostrarResultadosBusqueda(resultados);
            }

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Error al buscar usuarios:\n" + e.getMessage(),
                    "Error de base de datos",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonBuscarUsuarioActionPerformed

    private void jButtonCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearUsuarioActionPerformed
        FormularioCreacionUsuarios formulario = new FormularioCreacionUsuarios(this);
        formulario.setVisible(true);
    }//GEN-LAST:event_jButtonCrearUsuarioActionPerformed

    private void jButtonEliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarUsuarioActionPerformed
        int filaSeleccionada = jTableUsuarios.getSelectedRow();
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this,
                    "Seleccione un usuario de la tabla para eliminar.",
                    "Ninguna selección",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        int usuId = (int) jTableUsuarios.getValueAt(filaSeleccionada, 0);
        String nombreUsuario = (String) jTableUsuarios.getValueAt(filaSeleccionada, 1);

        int confirmacion = JOptionPane.showConfirmDialog(this,
                "¿Está seguro de eliminar el usuario '" + nombreUsuario + "'?",
                "Confirmar eliminación",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        if (confirmacion != JOptionPane.YES_OPTION) {
            return;
        }

        try {
            UsuarioDAO usuarioDAO = new UsuarioDAO();
            usuarioDAO.eliminar(usuId);

            JOptionPane.showMessageDialog(this,
                    "Usuario eliminado exitosamente.",
                    "Éxito",
                    JOptionPane.INFORMATION_MESSAGE);

            refrescarTabla();

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Error al eliminar el usuario:\n" + e.getMessage(),
                    "Error de base de datos",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonEliminarUsuarioActionPerformed

    private void jButtonEditarEditarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarEditarUsuarioActionPerformed
        int filaSeleccionada = jTableUsuarios.getSelectedRow();
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this,
                    "Seleccione un usuario de la tabla para editar.",
                    "Ninguna selección",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            int usuId = (int) jTableUsuarios.getValueAt(filaSeleccionada, 0);
            UsuarioDAO usuarioDAO = new UsuarioDAO();
            modelos.Usuario usuario = usuarioDAO.obtenerPorId(usuId);

            if (usuario == null) {
                JOptionPane.showMessageDialog(this,
                        "No se encontró el usuario seleccionado.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            FormularioCreacionUsuarios formulario = new FormularioCreacionUsuarios(this, usuario);
            formulario.setVisible(true);

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Error al cargar el usuario para edición:\n" + e.getMessage(),
                    "Error de base de datos",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonEditarEditarUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscarUsuario;
    private javax.swing.JButton jButtonCrearUsuario;
    private javax.swing.JButton jButtonEditarEditarUsuario;
    private javax.swing.JButton jButtonEliminarUsuario;
    private javax.swing.JButton jButtonRestablecer;
    private javax.swing.JPanel jPanelClientes3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTableUsuarios;
    // End of variables declaration//GEN-END:variables
}
