/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

/**
 *
 * @author USUARO_PC
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private VentanaLogin login;

    public VentanaPrincipal(VentanaLogin login) {
        this.login = login;
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                login.setVisible(true);
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonUsuarios = new javax.swing.JButton();
        jButtonClientes = new javax.swing.JButton();
        jButtonCitas = new javax.swing.JButton();
        jButtonEmpleados = new javax.swing.JButton();
        jButtonFacturacion = new javax.swing.JButton();
        jButtonServicios = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(0, 153, 204));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        background.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 0));

        jButtonUsuarios.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jButtonUsuarios.setText("Usuarios");
        jButtonUsuarios.setPreferredSize(new java.awt.Dimension(76, 24));
        jButtonUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUsuariosActionPerformed(evt);
            }
        });
        background.add(jButtonUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 190, 40));

        jButtonClientes.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jButtonClientes.setText("Clientes");
        jButtonClientes.setPreferredSize(new java.awt.Dimension(76, 24));
        jButtonClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClientesActionPerformed(evt);
            }
        });
        background.add(jButtonClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 190, 40));

        jButtonCitas.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jButtonCitas.setText("Citas");
        jButtonCitas.setPreferredSize(new java.awt.Dimension(76, 24));
        jButtonCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCitasActionPerformed(evt);
            }
        });
        background.add(jButtonCitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 190, 40));

        jButtonEmpleados.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jButtonEmpleados.setText("Empleados");
        jButtonEmpleados.setPreferredSize(new java.awt.Dimension(76, 24));
        jButtonEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEmpleadosActionPerformed(evt);
            }
        });
        background.add(jButtonEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 190, 40));

        jButtonFacturacion.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jButtonFacturacion.setText("Facturación");
        jButtonFacturacion.setPreferredSize(new java.awt.Dimension(76, 24));
        jButtonFacturacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFacturacionActionPerformed(evt);
            }
        });
        background.add(jButtonFacturacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 190, 40));

        jButtonServicios.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jButtonServicios.setText("Servicios");
        jButtonServicios.setPreferredSize(new java.awt.Dimension(76, 24));
        jButtonServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonServiciosActionPerformed(evt);
            }
        });
        background.add(jButtonServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 190, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\USUARO_PC\\Documents\\NetBeansProjects\\Clinica_Dental\\src\\main\\java\\images\\imagen2.jpeg")); // NOI18N
        background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 370, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 526, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUsuariosActionPerformed
        VentanaUsuarios usuarios = new VentanaUsuarios(this);
        usuarios.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonUsuariosActionPerformed

    private void jButtonClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClientesActionPerformed
        VentanaClientes clientes = new VentanaClientes(this);
        clientes.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonClientesActionPerformed

    private void jButtonCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCitasActionPerformed
        VentanaCitas citas = new VentanaCitas(this);
        citas.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCitasActionPerformed

    private void jButtonEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEmpleadosActionPerformed
        VentanaEmpleados empleados = new VentanaEmpleados(this);
        empleados.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonEmpleadosActionPerformed

    private void jButtonFacturacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFacturacionActionPerformed
        VentanaFacturacion facturacion = new VentanaFacturacion(this);
        facturacion.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonFacturacionActionPerformed

    private void jButtonServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonServiciosActionPerformed
        VentanaServicios servicios = new VentanaServicios(this);
        servicios.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonServiciosActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton jButtonCitas;
    private javax.swing.JButton jButtonClientes;
    private javax.swing.JButton jButtonEmpleados;
    private javax.swing.JButton jButtonFacturacion;
    private javax.swing.JButton jButtonServicios;
    private javax.swing.JButton jButtonUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
