/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import javax.swing.JOptionPane;

/**
 *
 * @author USUARO_PC
 */
public class VentanaLogin extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public VentanaLogin() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);

        jPanel1.setFocusable(true);
        jPanel1.requestFocusInWindow();
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTxtBienvenido = new javax.swing.JLabel();
        jLabelTxtInicioSesion = new javax.swing.JLabel();
        jTextFieldNombreUsuario = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jPasswordContrasena = new javax.swing.JPasswordField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabelfoto1 = new javax.swing.JLabel();
        jButtonIniciarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabelTxtBienvenido.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        jLabelTxtBienvenido.setText("Bienvenido ");

        jLabelTxtInicioSesion.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabelTxtInicioSesion.setText("Iniciar Sesión");

        jTextFieldNombreUsuario.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldNombreUsuario.setText("Ingrese su nombre de usuario");
        jTextFieldNombreUsuario.setBorder(null);
        jTextFieldNombreUsuario.setSelectionColor(new java.awt.Color(0, 0, 0));
        jTextFieldNombreUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldNombreUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNombreUsuarioFocusLost(evt);
            }
        });
        jTextFieldNombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreUsuarioActionPerformed(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        jPasswordContrasena.setBorder(null);
        jPasswordContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordContrasenaActionPerformed(evt);
            }
        });

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));

        jLabelfoto1.setIcon(new javax.swing.ImageIcon("C:\\Users\\USUARO_PC\\Documents\\NetBeansProjects\\Clinica_Dental\\src\\main\\java\\images\\imagen1.jpeg")); // NOI18N

        jButtonIniciarSesion.setFont(new java.awt.Font("Roboto SemiBold", 1, 14)); // NOI18N
        jButtonIniciarSesion.setText("ENTRAR");
        jButtonIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSeparator4)
                        .addComponent(jPasswordContrasena)
                        .addComponent(jSeparator2)
                        .addComponent(jLabelTxtInicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelTxtBienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldNombreUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE))
                    .addComponent(jButtonIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelfoto1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabelTxtBienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTxtInicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jTextFieldNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPasswordContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jButtonIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabelfoto1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNombreUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNombreUsuarioFocusGained
        if ("Ingrese su nombre de usuario".equals(jTextFieldNombreUsuario.getText())) {
            jTextFieldNombreUsuario.setText("");
            jTextFieldNombreUsuario.setForeground(java.awt.Color.BLACK);
        }
    }//GEN-LAST:event_jTextFieldNombreUsuarioFocusGained

    private void jTextFieldNombreUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNombreUsuarioFocusLost
        if (jTextFieldNombreUsuario.getText().isEmpty()) {
            jTextFieldNombreUsuario.setText("Ingrese su nombre de usuario");
            jTextFieldNombreUsuario.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_jTextFieldNombreUsuarioFocusLost

    private void jTextFieldNombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreUsuarioActionPerformed

    }//GEN-LAST:event_jTextFieldNombreUsuarioActionPerformed

    private void jPasswordContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordContrasenaActionPerformed

    private void jButtonIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarSesionActionPerformed
        try {
            String usuario = jTextFieldNombreUsuario.getText().trim();
            String password = new String(jPasswordContrasena.getPassword()).trim();

            if (usuario.isEmpty() || password.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "Usuario y contraseña son obligatorios",
                        "Error",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }

            // HASH de la contraseña ingresada
            String hash = utilidades.PasswordUtil.hashPassword(password);

            modelos.UsuarioDAO dao = new modelos.UsuarioDAO();
            modelos.Usuario u = dao.autenticar(usuario, hash);

            if (u != null) {
                VentanaPrincipal principal = new VentanaPrincipal(this);
                principal.setVisible(true);
                this.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(this,
                        "Usuario o contraseña incorrectos",
                        "Acceso denegado",
                        JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Error al iniciar sesión",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonIniciarSesionActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIniciarSesion;
    private javax.swing.JLabel jLabelTxtBienvenido;
    private javax.swing.JLabel jLabelTxtInicioSesion;
    private javax.swing.JLabel jLabelfoto1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordContrasena;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextFieldNombreUsuario;
    // End of variables declaration//GEN-END:variables
}
