/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import controladores.ServicioControl;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelos.Servicio;
import modelos.ServicioDAO;

/**
 *
 * @author USUARO_PC
 */
public class VentanaServicios extends javax.swing.JFrame {

    private VentanaPrincipal ventanaPrincipal;

    public VentanaServicios(VentanaPrincipal ventanaPrincipal) {
        this.ventanaPrincipal = ventanaPrincipal;
        initComponents();
        configurarTabla();
        configurarCierre();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    private void configurarTabla() {
        String[] columnas = {
            "ID",
            "Nombre",
            "Precio",
            "IVA",
            "Estado"
        };

        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(
                null, columnas
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        try {
            ServicioDAO servicioDAO = new ServicioDAO();
            List<Servicio> servicios = servicioDAO.listarTodos();

            for (Servicio s : servicios) {
                // Formatear precio a 2 decimales
                String precio = String.format("%.2f", s.getSerPrecio());

                // Convertir IVA a texto legible
                String iva = (s.getSerIva() == 'S') ? "Sí" : "No";

                // Convertir estado a texto legible
                String estado = s.getEstadoTexto(); // "Activo" o "Inactivo"

                Object[] fila = {
                    s.getSerId(),
                    s.getSerNombre(),
                    precio,
                    iva,
                    estado
                };

                modelo.addRow(fila);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                    "Error al cargar los servicios desde la base de datos:\n" + e.getMessage(),
                    "Error de conexión",
                    JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }

        jTableServicios.setModel(modelo);
    }

    private void actualizarTablaConServicios(List<Servicio> servicios) {
        // Definir columnas
        String[] columnas = {
            "ID", "Nombre", "Precio", "IVA", "Estado"
        };

        // Crear modelo de tabla
        DefaultTableModel modelo = new DefaultTableModel(null, columnas) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        // Llenar la tabla con los servicios
        for (Servicio s : servicios) {
            String ivaStr = (s.getSerIva() == 'S') ? "Sí" : "No";
            String estadoStr = (s.getSerEstado() == 'A') ? "Activo" : "Inactivo";

            Object[] fila = {
                s.getSerId(),
                s.getSerNombre(),
                String.format("$ %.2f", s.getSerPrecio()),
                ivaStr,
                estadoStr
            };
            modelo.addRow(fila);
        }

        // Asignar el modelo a la tabla
        jTableServicios.setModel(modelo);
    }

    public void refrescarTabla() {
        configurarTabla();
    }

    private void configurarCierre() {
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                ventanaPrincipal.setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelClientes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableServicios = new javax.swing.JTable();
        jButtonRestablecer = new javax.swing.JButton();
        jButtonBuscarServicio = new javax.swing.JButton();
        jButtonIngresarServicio = new javax.swing.JButton();
        jButtonEliminarServicio = new javax.swing.JButton();
        jButtonEditarServicio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelClientes.setBackground(new java.awt.Color(51, 153, 255));

        jTableServicios.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jTableServicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableServicios.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTableServicios);

        jButtonRestablecer.setText("Restablecer");
        jButtonRestablecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRestablecerActionPerformed(evt);
            }
        });

        jButtonBuscarServicio.setText("Buscar");
        jButtonBuscarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarServicioActionPerformed(evt);
            }
        });

        jButtonIngresarServicio.setText("Ingresar Servicio");
        jButtonIngresarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIngresarServicioActionPerformed(evt);
            }
        });

        jButtonEliminarServicio.setText("Eliminar");
        jButtonEliminarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarServicioActionPerformed(evt);
            }
        });

        jButtonEditarServicio.setText("Editar");
        jButtonEditarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarServicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelClientesLayout = new javax.swing.GroupLayout(jPanelClientes);
        jPanelClientes.setLayout(jPanelClientesLayout);
        jPanelClientesLayout.setHorizontalGroup(
            jPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClientesLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonRestablecer, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscarServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonIngresarServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEliminarServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEditarServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );
        jPanelClientesLayout.setVerticalGroup(
            jPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
            .addGroup(jPanelClientesLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jButtonRestablecer, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonBuscarServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonIngresarServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonEliminarServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonEditarServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRestablecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRestablecerActionPerformed
        configurarTabla();
    }//GEN-LAST:event_jButtonRestablecerActionPerformed

    private void jButtonBuscarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarServicioActionPerformed
        String criterio = JOptionPane.showInputDialog(
                this,
                "Ingrese el nombre o ID del servicio a buscar:",
                "Buscar Servicio",
                JOptionPane.QUESTION_MESSAGE
        );

        if (criterio == null || criterio.trim().isEmpty()) {
            return; // Canceló o dejó vacío
        }

        try {
            // Cargar todos los servicios una sola vez
            ServicioControl servicioControl = new ServicioControl();
            List<Servicio> todosServicios = servicioControl.listarTodos();
            List<Servicio> coincidencias = new ArrayList<>();

            String busqueda = criterio.trim().toLowerCase();

            for (Servicio s : todosServicios) {
                // Buscar por nombre
                if (s.getSerNombre().toLowerCase().contains(busqueda)) {
                    coincidencias.add(s);
                } // Buscar por ID (si es numérico)
                else if (busqueda.matches("\\d+")) {
                    int idBuscado = Integer.parseInt(busqueda);
                    if (s.getSerId() == idBuscado) {
                        coincidencias.add(s);
                    }
                }
            }

            if (coincidencias.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "No se encontraron servicios con el criterio: \"" + criterio.trim() + "\"",
                        "Sin resultados",
                        JOptionPane.INFORMATION_MESSAGE);

            } else {
                // Actualizar la tabla SOLO con los resultados
                actualizarTablaConServicios(coincidencias);

            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                    "Error al buscar servicios:\n" + e.getMessage(),
                    "Error de base de datos",
                    JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButtonBuscarServicioActionPerformed

    private void jButtonIngresarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIngresarServicioActionPerformed
        FormularioRegistroServicios formulario = new FormularioRegistroServicios(this);
        formulario.setVisible(true);
    }//GEN-LAST:event_jButtonIngresarServicioActionPerformed

    private void jButtonEliminarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarServicioActionPerformed
        int filaSeleccionada = jTableServicios.getSelectedRow();
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this,
                    "Seleccione un servicio de la tabla para eliminar.",
                    "Ninguna selección",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        int serId = (int) jTableServicios.getValueAt(filaSeleccionada, 0);
        String nombreServicio = (String) jTableServicios.getValueAt(filaSeleccionada, 1);

        int confirmacion = JOptionPane.showConfirmDialog(this,
                "¿Está seguro de eliminar el servicio '" + nombreServicio + "'?\n"
                + "Esta acción no se puede deshacer.",
                "Confirmar eliminación",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        if (confirmacion != JOptionPane.YES_OPTION) {
            return;
        }

        try {
            ServicioDAO servicioDAO = new ServicioDAO();
            servicioDAO.eliminar(serId);

            JOptionPane.showMessageDialog(this,
                    "Servicio eliminado exitosamente.",
                    "Éxito",
                    JOptionPane.INFORMATION_MESSAGE);

            refrescarTabla();

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Error al eliminar el servicio:\n" + e.getMessage(),
                    "Error de base de datos",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonEliminarServicioActionPerformed

    private void jButtonEditarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarServicioActionPerformed
        int filaSeleccionada = jTableServicios.getSelectedRow();
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this,
                    "Seleccione un servicio de la tabla para editar.",
                    "Ninguna selección",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            int serId = (int) jTableServicios.getValueAt(filaSeleccionada, 0);
            ServicioDAO servicioDAO = new ServicioDAO();
            modelos.Servicio servicio = servicioDAO.obtenerPorId(serId);

            if (servicio == null) {
                JOptionPane.showMessageDialog(this,
                        "No se encontró el servicio seleccionado.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            FormularioRegistroServicios formulario = new FormularioRegistroServicios(this, servicio);
            formulario.setVisible(true);

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Error al cargar el servicio para edición:\n" + e.getMessage(),
                    "Error de base de datos",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonEditarServicioActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscarServicio;
    private javax.swing.JButton jButtonEditarServicio;
    private javax.swing.JButton jButtonEliminarServicio;
    private javax.swing.JButton jButtonIngresarServicio;
    private javax.swing.JButton jButtonRestablecer;
    private javax.swing.JPanel jPanelClientes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableServicios;
    // End of variables declaration//GEN-END:variables
}
